package webhook.teamcity.server.rest.data;

import webhook.teamcity.server.rest.model.template.ErrorResult;
import webhook.teamcity.server.rest.model.webhook.ProjectWebHookFilter;

public class WebHookFilterValidator {

	public static ErrorResult validateNewFilter(ProjectWebHookFilter newFilter, ErrorResult result) {
		
		if (newFilter.getId() != null) {
			result.addError("id-empty", "The filter id must be empty. It will be generated by Teamcity");
		}

		return validateFilter(newFilter, result);
	}

	public static ErrorResult validateFilter(ProjectWebHookFilter updatedFilter, ErrorResult result) {

		if (updatedFilter.getValue() == null || updatedFilter.getValue().trim().isEmpty()) {
			result.addError("value", "The filter value cannot be empty.");
		}
		if (updatedFilter.getRegex() == null || updatedFilter.getRegex().trim().isEmpty()) {
			result.addError("regex", "The filter regex cannot be empty.");
		}
		
		return result;
	}
	
}
