#%RAML 0.8
 
title: World Music API
baseUri: http://example.api.com/{version}
version: v1

schemas:
  - halLink: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "A link",
        "properties": {
          "href":  { "type": "string" }
        }
      }
  - song: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "A canonical song",
        "properties": {
          "title":  { "type": "string", "description": "The title of the Song"},
          "artist": { "type": "string" },
          "link": { "$ref": "halLink", "targetType": "artist" }
        },
        "required": [ "title", "artist" ]
      }
  - artist: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "A canonical song",
        "properties": {
          "name": { "type": "string" }
        }
      }
